export const estadoProducto = [
  { id: 1, estado: "Nuevo" },
  { id: 2, estado: "Usado" },
  { id: 3, estado: "Reacondicionado" },
  { id: 4, estado: "Como Nuevo" },
  { id: 5, estado: "Muy Bueno" },
  { id: 6, estado: "Bueno" },
  { id: 7, estado: "Aceptable" },
  { id: 8, estado: "Para Repuestos" },
  { id: 9, estado: "En Embalaje Original" },
  { id: 10, estado: "Sin Embalaje Original" },
  { id: 11, estado: "Con Defectos" },
  { id: 12, estado: "Restaurado" },
  { id: 13, estado: "Sin Uso" },
  { id: 14, estado: "Dañado" },
  { id: 15, estado: "Caducado" },
];

export const categoriaProducto = [
  { id: 1, categoria: "Accesorios" },
  { id: 2, categoria: "Alimentación" },
  { id: 3, categoria: "Audio y Vídeo" },
  { id: 4, categoria: "Bebés" },
  { id: 5, categoria: "Belleza" },
  { id: 6, categoria: "Cámaras" },
  { id: 7, categoria: "Coches y motos" },
  { id: 8, categoria: "Deportes" },
  { id: 9, categoria: "Electrodomésticos" },
  { id: 10, categoria: "Electrónica" },
  { id: 11, categoria: "Herramientas" },
  { id: 12, categoria: "Hogar" },
  { id: 13, categoria: "Iluminación" },
  { id: 14, categoria: "Informática" },
  { id: 15, categoria: "Jardín" },
  { id: 16, categoria: "Joyería" },
  { id: 17, categoria: "Juguetes" },
  { id: 18, categoria: "Libros" },
  { id: 19, categoria: "Música" },
  { id: 20, categoria: "Oficina" },
  { id: 21, categoria: "Ropa" },
  { id: 22, categoria: "Salud" },
  { id: 23, categoria: "Software" },
  { id: 24, categoria: "Telefonía" },
  { id: 25, categoria: "TV" },
  { id: 26, categoria: "Vehículos" },
  { id: 27, categoria: "Videojuegos" },
  { id: 28, categoria: "Otros" },
];
